// Change these values for face-scan design tuning.
export const FACE_SCAN_CONFIG = {
  timing: {
    duration: 7000,
    ease: 'easeInOutSine',
  },
  image: {
    cleanFilter: 'contrast(1.04) brightness(1) saturate(1.05)',
    cleanAlpha: 1,
  },
  // Mask values control where pixels appear. Raise values to ignore more background.
  mask: {
    alpha: 8,
    luminance: 32,
    colorRange: 18,
  },
  mosaic: {
    density: 38,
    minSize: 12,
    revealOverlap: 0.35,
    noiseCutoff: 0.26,
    depthNoise: 0.28,
    alphaMin: 0.08,
    alphaMax: 0.3,
    depthAlpha: 0.18,
    distanceAlpha: 0.06,
    colorMin: 28,
    colorRange: 34,
    scaleMin: 0.28,
    scaleMax: 0.86,
    waveSpeed: 2.4,
    centerWave: 9,
    phaseSeed: 7.31,
  },
  rebuild: {
    density: 72,
    minSize: 6,
    revealOverlap: 0.5,
    noiseSeed: 3.73,
    phaseSeed: 11.13,
    noiseCutoff: 0.18,
    distanceNoise: 0.56,
    waveSpeed: 3.2,
    scaleMin: 0.44,
    scaleWave: 0.28,
    scaleNoise: 0.42,
    alphaMax: 0.72,
    alphaBase: 0.32,
    alphaNoise: 0.42,
    markerNoise: 0.72,
    markerColor: 'rgba(185, 195, 205, 0.88)',
    markerAlpha: 0.28,
    markerScale: 0.34,
  },
  // Line values control scanner design.
  line: {
    width: 2,
    inset: 0.05,
    glow: 20,
    bandHeight: 0.18,
    bandPixelHeight: 20,
    bandAlpha: 0.22,
  },
}
