export const GEOMETRIC_SCAN_CONFIG = {
  timing: {
    duration: 7000,
  },
  grid: {
    icons: [
      'menu',
      'sparkles',
      'layout-dashboard',
      'loader',
      'star',
      'zap',
      'layout-grid',
      'flame',
      'sparkle',
      'workflow',
      'car',
      'blocks',
      'audio-lines',
      'bot-message-square',
      'chart-pie',
      'utensils',
      'component',
      'hat-glasses',
      'clock-fading',
      'minimize',
      'container',
      'pyramid',
      'radius',
      'activity',
      'disc',
      'eject',
      'infinity',
      'shell',
      'stone',
      'compass',
      'locate',
      'cctv',
      'swatch-book',
      'omega',
      'lens-convex',
      'orbit',
      'bomb',
      'shapes',
      'binary',
      'code',
      'code-xml',
      'paint-roller',
      'rainbow',
      'circle-dashed',
    ],
  },
}
